config/routes.rb
Rails.application.routes.draw do
  namespace :authentication, path: '', as: '' do
    resources :users, only: [:new, :create], path: '/register', path_names: { new: '/' }
    resources :sessions, only: [:new, :create, :destroy], path: '/login', path_names: { new: '/' }
  end

  resources :favorites, only: [:index, :create, :destroy], param: :product_id
  resources :users, only: :show, path: '/user', param: :username
  resources :categories, except: :show
  resources :products, path: '/'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true

  has_many :products, dependent: :restrict_with_exception
end

app/models/concerns/favoritable.rb
module Favoritable
  extend ActiveSupport::Concern

included do
  has_many :favorites, dependent: :destroy
  
  def favorite!
    favorites.create(user: Current.user)
  end

  def unfavorite!
    favorite.destroy
  end

  def favorite
    favorites.find_by(user: Current.user)
  end
  end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
 validates :user, uniqueness: { scope: :product }
 
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model
  include Favoritable
  pg_search_scope :search_full_text, against: {
    title: 'A',
    description: 'B',
  }

  ORDER_BY = {
    newest: "created_at DESC",
    expensive: "price DESC",
    cheapest: "price ASC"
 }

has_one_attached :photo

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true

  belongs_to :category
  belongs_to :user, default: -> { Current.user }

  def owner?
    user_id == Current.user&.id
  end

  def broadcast
    broadcast_replace_to self, partial: "products/product_details", locals: { product: self }
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true,
  format: {
    with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,
    message: :invalid
  }
   validates :username, presence: true, uniqueness: true,
   length: { in: 3..15 },
   format: {
     with: /\A[a-z0-9A-Z]+\z/,
     message: :invalid
   }
  validates :password, length: { minimum: 6 }, if: :password_digest_changed?

  has_many :products, dependent: :destroy
  has_many :favorites, dependent: :destroy


  before_save :downcase_attributes

  def downcase_attributes
    self.username = username.downcase
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
include Authentication
include Authorization
include Pagy::Backend
include Error
end

app/controllers/authentication/sessions_controller.rb
class Authentication::SessionsController < ApplicationController
skip_before_action :protect_pages

  def new
  end

  def create
  @user = User.find_by("email = :login OR username = :login", { login: params[:login] })

  if @user&.authenticate(params[:password])
    session[:user_id] = @user.id
    redirect_to products_path, notice: 'Welcome!'
  else
    redirect_to new_session_path, alert: 'Invalid login!'
   end
  end

  def destroy
    session.delete(:user_id)

    redirect_to products_path, notice: 'Destroyed!'
  end
end

app/controllers/authentication/users_controller.rb
class Authentication::UsersController < ApplicationController
  skip_before_action :protect_pages

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    FetchCountryJob.perform_later(@user.id, request.remote_ip)

    if @user.save
      UserMailer.with(user: @user).welcome.deliver_later
    session[:user_id] = @user.id
      redirect_to products_path, notice: 'Your acount has been created!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :password)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authorize!
  def index
    @categories = Category.all. order(name: :asc)
  end

  def new
    @category = Category.new
  end

  def edit
    category
  end

  def create
    @category = Category.new(category_params)

      if @category.save
         redirect_to categories_url, notice: "Category was successfully created."
      else
        render :new, status: :unprocessable_entity
    end
  end

  def update
      if category.update(category_params)
        redirect_to categories_url, notice: "Category was successfully updated."
      else
     render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    category.destroy!

     redirect_to categories_url, notice: "Category was successfully destroyed."
  end

  private

    def category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

included do
  before_action :set_current_user
  before_action :protect_pages

    private

    def set_current_user
      Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def protect_pages
      redirect_to new_session_path, alert: 'you have to login or create an acount' unless Current.user
    end
  end
end

app/controllers/concerns/authorization.rb
module Authorization
  extend ActiveSupport::Concern

included do
  class NotAuthorizedError < StandardError; end

  rescue_from NotAuthorizedError do
    redirect_to products_path, alert: 'not_authorized!'
    end

    private

    def authorize! record = nil
      is_allowed = "#{controller_name.singularize}Policy".classify.constantize.new(record).send(action_name)
       raise NotAuthorizedError unless is_allowed
     end
  end
end

app/controllers/concerns/error.rb
module Error
  extend ActiveSupport::Concern

included do
  rescue_from ActiveRecord::RecordNotFound do
    redirect_to products_path, alert: 'It has not been found'
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
def index

end

  def create
    product.favorite!
    respond_to do |format|
      format.html do
        redirect_to product_path(product)
      end
      format.turbo_stream do
      render turbo_stream: turbo_stream.replace("favorite", partial: "products/favorite", locals: { product: product} )
      end
    end
  end

  def destroy
     product.unfavorite!
     respond_to do |format|
      format.html do
        redirect_to product_path(product), status: :see_other
      end
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace("favorite", partial: "products/favorite", locals: { product: product} )
      end
    end
  end

  private

  def product
    @product ||= Product.find(params[:product_id])
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :protect_pages, only: [:index, :show]

  def index
    @categories = Category.order(name: :asc)
    @pagy, @products = pagy_countless(FindProducts.new.call(product_params_index), items: 12)
      end

 def show
  product
 end

 def new
   @product = Product.new
 end

 def create
   @product = Product.new(product_params)

   if @product.save
   redirect_to products_path, notice: 'Your product has been created successfully'
   else
render :new, status: :unprocessable_entity
   end
 end

 def edit
  authorize! product
 end

 def update
  authorize! product
  if product.update(product_params)
    product.broadcast
    redirect_to products_path, notice: 'Your product has been successfully updated'
  else
render :edit, status: :unprocessable_entity
  end
 end

 def destroy
  authorize! product
  product.destroy

  redirect_to products_path, notice: 'Your product has been successfully removed', status: :see_other
 end

 private


 def product_params
   params.require(:product).permit(:title, :description, :price, :photo, :category_id)
 end

 def product_params_index
  params.permit(:category_id, :min_price, :max_price, :query_text, :order_by, :page, :favorites, :user_id)
 end

 def product
  @product ||= Product.find(params[:id])
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :protect_pages, only: :show

  def show
  @user = User.find_by!(username: params[:username])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
include Pagy::Frontend
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/authentication/users/new.html.erb
<%= form_with(model: @user) do |form| %>
 <% @user.errors.full_messages.each do |error| %>
<div>
    <%= error %>
</div>
  <% end %>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email, required: true %>
  </div>

   <div>
    <%= form.label :username %>
    <%= form.text_field :username, required: true %>
  </div>

   <div>
    <%= form.label :password %>
    <%= form.password_field :password, required: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
    <%= category.name %>
    <%= link_to 'Edit', edit_category_path(category) %>
    <%= link_to 'Delete', category_path(category), data: {
    turbo_method: :delete,
    turbo_confirm: 'You are sure?'
} %>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<h1>Categories</h1>

<%= render partial: 'category', collection: @categories %>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/favorites/index.html.erb
<h1>My Favorites</h1>

<%= turbo_frame_tag :products, src: products_path(favorites: true) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ViolethStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-200">
    <%= render 'shared/flash' %>
    <%= render 'shared/header' %>
   <div class="lg:container lg:mx-auto">
     <%= yield %>
   </div>
   <%= turbo_frame_tag 'modal' %>
  </body>
</html>

app/views/products/_favorite.html.erb
<div id="favorite">  
<% if product.favorite %>
<%= link_to '💔', favorite_path(product.id), data: {
    turbo_method: :delete,
} %>
<% else %> 
<%= link_to '❤️', favorites_path(product_id: product.id), data: {
    turbo_method: :post,
} %>
<% end %>
</div>

app/views/products/_form.html.erb
 <%= form_with model: @product do |form| %>
 <% @product.errors.full_messages.each do |error| %>
<div>
    <%= error %>
</div>

<% end %>

 <div>
<%= form.label :title %>
<%= form.text_field :title %>
</div>

 <div>
<%= form.label :description %>
<%= form.text_area :description %>
</div>

 <div>
<%= form.label :price %>
<%= form.number_field :price %>
</div>

 <div>
<%= form.collection_select :category_id, Category.all.order(name: :asc), :id, :name %>
</div>

 <div>
<%= form.label :photo %>
<%= form.file_field :photo %>
</div>

<%= form.submit%>
 <% end %>

app/views/products/_product.html.erb
<%= link_to product_path(product), class: "product bg-white mb-2 rounded sm:w-[calc(25%_-_.5rem)] lg:w-[calc(33.33333_-_.5rem)]", 'data-turbo-frame': '_top' do %>
 <%= image_tag(product.photo.attached? ? product.photo : 'placeholder1.jpg', class: "w-full h-60 object-cover") %>
 <div class="m-2">
    <span class="font-bold text-xl"><%= product.price %>$</span>
    <h2 class=""><%= product.title %></h2>
    <p class="text-gray-500 text-sm mt-2"><%= product.description %></p>
 </div>
<% end %>

app/views/products/_product_details.html.erb
<div id= "<%= dom_id(product)%>" >
<%= image_tag product.photo, width: 200 if product.photo.attached?  %>

<h1 class= 'title'><%= product.title %></h1>

<p class= 'description'><%= product.description %></p>

<span class= 'price'><%= product.price %>$</span>
</div>

app/views/products/edit.html.erb
<h2>Edit product</h2>
 
<%= render 'form' %>

app/views/products/index.html.erb
<%= turbo_frame_tag 'home' do %>
  <%= form_with url: products_path, method: :get do |form| %>
    <%= form.text_field :query_text, placeholder: 'What do you want to look for?', onChange: 'this.form.requestSubmit()', value: params[:query_text], class:"w-full my-2 rounded-full border-gray-200" %>

<div class="flex">
    <%= form.number_field :min_price, placeholder: 'Min_price', onChange: 'this.form.requestSubmit()', value: params[:min_price], class:"w-1/3 rounded-full border-gray-200" %>

    <%= form.number_field :max_price, placeholder: 'Max_price', onChange: 'this.form.requestSubmit()', value: params[:max_price], class:"w-1/3 rounded-full border-gray-200 mx-2" %>

    <%= form.select :order_by, options_for_select(Product::ORDER_BY.keys.map{ |order| [order, order] }, params[:order_by]), {}, { onChange: 'this.form.requestSubmit()', class:"w-1/3 rounded-full border-gray-200 text-gray-500" } %>
    </div>
  <% end %>

  <div class="flex overflow-x-scroll gap-2 my-4">  
  <%= render(CategoryComponent.new) %>
 
 <%= render(CategoryComponent.with_collection(@categories)) %>
</div>

<%= turbo_frame_tag :products, class:"flex flex-col m-2" do %>
 <%= turbo_frame_tag "products-#{@pagy.page}", class: "products flex flex-col w-full sm:flex-row sm:flex-wrap sm:gap-x-2" do %> 
  <%= render partial: 'product', collection: @products %>
    <%= turbo_frame_tag "products-#{@pagy.next}", class: "products flex flex-col w-full sm:flex-row sm:flex-wrap sm:gap-x-2", src: pagy_url_for(@pagy, @pagy.next), loading: :lazy if @pagy.next %>
   <% end %>
  <% end %>
<% end %>

app/views/products/new.html.erb
<%= turbo_frame_tag "modal" do %>
<div data-controller="modal">  
    <div data-action="click->modal#close" class="fixed z-10 w-full h-full top-0 left-0 bg-black bg-opacity-40"></div>
       <div data-modal-target="sidebar" class="fixed top-0 right-0 z-20 w-1/2 sm:w-3/6 lg:w-2/6 h-full bg-white overflow-y-scroll shadow flex flex-col ease-in-out duration-300 p-5 translate-x-full">  
        <p data-action="click->modal#close">❌</p> 
     <h2 class="font-bold mb-4">Add product</h2>
 
     <%= render 'form' %>
       </div>
   </div>
<% end %>

app/views/products/show.html.erb
 <%= render partial: 'products/product_details', locals: { product: @product }  %>

<%= link_to 'Edit product', edit_product_path(@product) if @product.owner? %>

<%= link_to 'Delete product', product_path(@product), data: {
    turbo_method: :delete,
    turbo_confirm: 'You are sure?'
} if @product.owner? %>

<%= link_to 'View more products', user_path(@product.user.username)%>

<%= render partial: 'favorite', locals: { product: @product} %>

<%= turbo_stream_from @product %>

app/views/shared/_flash.html.erb
<% if alert || notice %>
  <% color = alert ? 'bg-red-400' : 'bg-green-400' %>
  <div class="fixed top-0 inset-x-0 m-4 z-30 pointer-events-none">
    <div class="flex flex-col items-end space-y-4">
      <div data-controller="alert" data-alert-dismiss-after-value="3000" data-alert-show-class="translate-x-0 opacity-100" data-alert-hide-class="translate-x-full opacity-0" class="ease-in-out duration-500 max-w-sm w-full shadow-lg rounded px-4 py-3 relative <%= color %> text-white pointer-events-auto translate-x-0 opacity-100">
        <div class="p-2">
          <div class="flex items-start">
            <div class="ml-3 w-0 flex-1 pt-0.5">
              <p class="text-sm leading-5 font-medium">
                <%= alert || notice %>
              </p>
            </div>
            <div class="ml-4 flex-shrink-0 flex">
              <button data-action="alert#close" class="inline-flex text-white focus:outline-none focus:text-gray-300 transition ease-in-out duration-150">
                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="bg-white flex justify-between items-center px-2" data-controller="menu">
   <%= link_to products_path do  %>
<h1 class="text-2x1 font-bold text-blue-500">Violeth Store</h1>
<% end %>
<button class="sm:hidden" data-action="click->menu#toggle"><%= image_tag 'icons/menu.svg', width: 35, height: 35 %></button>

<div class="hidden sm:block">  
<%= render partial: 'shared/items' %>
   </div>

<!--Menu mobile -->
   <div class="sm:hidden absolute bg-white top-0 right-0 shadow z-10 h-full flex flex-col min-w-[45%] overflow-y-scroll ease-in-out duration-200 p-5 translate-x-full" data-menu-target="items">
      <button class="mb-4" data-action="click->menu#toggle"><%= image_tag 'icons/close.svg', width: 35, height: 35 %></button>
<%= render partial: 'shared/items' %>
   </div>
</div>

app/views/shared/_items.html.erb
<%= link_to 'Add product', new_product_path, class:"mx-2 text-teal-500 font-bold", data: { turbo_frame: "modal" } if Current.user %>
<%= link_to 'Favorites', favorites_path, class:"mx-2 text-teal-500 font-bold" if Current.user %>
<%= link_to 'Categories', categories_path, class:"mx-2 text-teal-500 font-bold" if Current.user&.admin? %>
<%= link_to 'Login', new_session_path, class:"mx-2 text-teal-500 font-bold" unless Current.user %>
<%= link_to 'Register', new_user_path, class:"mx-2 text-teal-500 font-bold" unless Current.user %>
<%= link_to 'Logout', session_path(Current.user.id), data: {
   turbo_method: :delete,
   turbo_comfirm: 'Confirm!'
}, class:"mx-2 text-red-600 font-bold" if Current.user %>

app/views/users/show.html.erb
<%= @user.username %>

  <%= turbo_frame_tag :products, src: products_path(user_id: @user.id) %>